Fixed make_parameters.jl bug
PoisotLab/BioEnergeticFoodWebs.jl pull request #14
Opened 2017-03-17 12:09 UTC by TomClegg94

There was a bug where providing a biomass index would result in metabolic rates ( `p[:x]` ) being equal to `inf`. 

**Summary of changes:**

1. changed the source of biomasses for the calculation of metabolic rates

2017-03-17 13:58 UTC, tpoisot commented
Good call :+1: -- can you add a test to make sure that this is covered?

2017-03-17 13:59 UTC, tpoisot commented
Closes #15 when merged.

2017-03-17 14:44 UTC, TomClegg94 commented
Done

2017-03-17 23:25 UTC, tpoisot requested changes
see the issue on line 46 in test/make_parameters.jl

2017-03-17 23:25 UTC, tpoisot commented on test/make_parameters.jl
> +  p_b = model_parameters(correct_network, bodymass = p[:bodymass)
this line should end with `])`, not `]`

2017-03-17 23:26 UTC, tpoisot commented
The change I suggested should make the test pass -- as soon as this is done, I'll submit a patched version (*0.3.1*) on monday.

2017-03-18 12:53 UTC, tpoisot approved these changes

2017-03-18 12:54 UTC, merged